export interface Database {
  public: {
    Tables: {
      // Tables will be defined below
      users: {
        Row: {
          id: string;
          email: string;
          created_at: string;
          updated_at: string;
          first_name: string | null;
          last_name: string | null;
          phone_number: string | null;
          property_address: string | null;
          bot_phone_number: string | null;
          subscription_tier: string;
          subscription_status: string;
          max_units: number;
          storage_used: number;
          storage_limit: number;
          cancellation_reason: string | null;
        };
        Insert: {
          id?: string;
          email: string;
          created_at?: string;
          updated_at?: string;
          first_name?: string | null;
          last_name?: string | null;
          phone_number?: string | null;
          property_address?: string | null;
          bot_phone_number?: string | null;
          subscription_tier?: string;
          subscription_status?: string;
          max_units?: number;
          storage_used?: number;
          storage_limit?: number;
          cancellation_reason?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          created_at?: string;
          updated_at?: string;
          first_name?: string | null;
          last_name?: string | null;
          phone_number?: string | null;
          property_address?: string | null;
          bot_phone_number?: string | null;
          subscription_tier?: string;
          subscription_status?: string;
          max_units?: number;
          storage_used?: number;
          storage_limit?: number;
          cancellation_reason?: string | null;
        };
      };
      units: {
        Row: {
          id: string;
          user_id: string;
          address: string;
          unit_number: string | null;
          rent_amount: number;
          status: string;
          tenant_name: string | null;
          tenant_email: string | null;
          tenant_phone: string | null;
          lease_start: string | null;
          lease_end: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          address: string;
          unit_number?: string | null;
          rent_amount?: number;
          status?: string;
          tenant_name?: string | null;
          tenant_email?: string | null;
          tenant_phone?: string | null;
          lease_start?: string | null;
          lease_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          address?: string;
          unit_number?: string | null;
          rent_amount?: number;
          status?: string;
          tenant_name?: string | null;
          tenant_email?: string | null;
          tenant_phone?: string | null;
          lease_start?: string | null;
          lease_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      maintenance_requests: {
        Row: {
          id: string;
          user_id: string;
          unit_id: string;
          title: string;
          description: string;
          status: string;
          priority: string;
          category: string | null;
          photos: string[] | null;
          notes: string | null;
          estimated_cost: number | null;
          actual_cost: number | null;
          assigned_to: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          unit_id: string;
          title: string;
          description: string;
          status?: string;
          priority?: string;
          category?: string | null;
          photos?: string[] | null;
          notes?: string | null;
          estimated_cost?: number | null;
          actual_cost?: number | null;
          assigned_to?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          unit_id?: string;
          title?: string;
          description?: string;
          status?: string;
          priority?: string;
          category?: string | null;
          photos?: string[] | null;
          notes?: string | null;
          estimated_cost?: number | null;
          actual_cost?: number | null;
          assigned_to?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      leads: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          email: string | null;
          phone: string | null;
          status: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          email?: string | null;
          phone?: string | null;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          email?: string | null;
          phone?: string | null;
          status?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      payments: {
        Row: {
          id: string;
          user_id: string;
          unit_id: string;
          amount: number;
          due_date: string;
          paid_date: string | null;
          status: string;
          late_fee: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          unit_id: string;
          amount: number;
          due_date: string;
          paid_date?: string | null;
          status?: string;
          late_fee?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          unit_id?: string;
          amount?: number;
          due_date?: string;
          paid_date?: string | null;
          status?: string;
          late_fee?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      leases: {
        Row: {
          id: string;
          user_id: string;
          unit_id: string;
          unit_number: string;
          tenant_id: string | null;
          tenant_name: string;
          tenant_email: string | null;
          tenant_phone: string | null;
          start_date: string;
          end_date: string;
          rent_amount: number;
          security_deposit: number;
          lease_type: string;
          status: string;
          notes: string | null;
          documents: Record<string, any> | null;
          terms: Record<string, any> | null;
          termination_reason: string | null;
          termination_date: string | null;
          renewal_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          unit_id: string;
          unit_number?: string;
          tenant_id?: string | null;
          tenant_name: string;
          tenant_email?: string | null;
          tenant_phone?: string | null;
          start_date: string;
          end_date: string;
          rent_amount?: number;
          security_deposit?: number;
          lease_type?: string;
          status?: string;
          notes?: string | null;
          documents?: Record<string, any> | null;
          terms?: Record<string, any> | null;
          termination_reason?: string | null;
          termination_date?: string | null;
          renewal_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          unit_id?: string;
          unit_number?: string;
          tenant_id?: string | null;
          tenant_name?: string;
          tenant_email?: string | null;
          tenant_phone?: string | null;
          start_date?: string;
          end_date?: string;
          rent_amount?: number;
          security_deposit?: number;
          lease_type?: string;
          status?: string;
          notes?: string | null;
          documents?: Record<string, any> | null;
          terms?: Record<string, any> | null;
          termination_reason?: string | null;
          termination_date?: string | null;
          renewal_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          landlord_user_id: string;
          tenant_phone: string;
          tenant_name: string | null;
          tenant_message: string;
          bot_response: string;
          timestamp: string;
          type: string;
          escalated: boolean;
          landlord_responded: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          landlord_user_id: string;
          tenant_phone?: string;
          tenant_name?: string | null;
          tenant_message: string;
          bot_response: string;
          timestamp?: string;
          type?: string;
          escalated?: boolean;
          landlord_responded?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          landlord_user_id?: string;
          tenant_phone?: string;
          tenant_name?: string | null;
          tenant_message?: string;
          bot_response?: string;
          timestamp?: string;
          type?: string;
          escalated?: boolean;
          landlord_responded?: boolean;
          created_at?: string;
        };
      };
      ai_usage: {
        Row: {
          id: string;
          user_id: string;
          request_date: string;
          requests_used: number;
          requests_limit: number;
          last_request_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          request_date: string;
          requests_used?: number;
          requests_limit?: number;
          last_request_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          request_date?: string;
          requests_used?: number;
          requests_limit?: number;
          last_request_at?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      payment_methods: {
        Row: {
          id: string;
          user_id: string;
          stripe_payment_method_id: string;
          stripe_customer_id: string;
          type: string | null;
          last4: string | null;
          brand: string | null;
          exp_month: number | null;
          exp_year: number | null;
          is_default: boolean;
          is_valid: boolean;
          card_brand: string | null;
          card_last4: string | null;
          card_exp_month: number | null;
          card_exp_year: number | null;
          billing_details: Record<string, any> | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          stripe_payment_method_id: string;
          stripe_customer_id: string;
          type?: string | null;
          last4?: string | null;
          brand?: string | null;
          exp_month?: number | null;
          exp_year?: number | null;
          is_default?: boolean;
          is_valid?: boolean;
          card_brand?: string | null;
          card_last4?: string | null;
          card_exp_month?: number | null;
          card_exp_year?: number | null;
          billing_details?: Record<string, any> | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          stripe_payment_method_id?: string;
          stripe_customer_id?: string;
          type?: string | null;
          last4?: string | null;
          brand?: string | null;
          exp_month?: number | null;
          exp_year?: number | null;
          is_default?: boolean;
          is_valid?: boolean;
          card_brand?: string | null;
          card_last4?: string | null;
          card_exp_month?: number | null;
          card_exp_year?: number | null;
          billing_details?: Record<string, any> | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoices: {
        Row: {
          id: string;
          user_id: string;
          subscription_id: string | null;
          stripe_invoice_id: string;
          stripe_charge_id: string | null;
          status: string;
          amount: number;
          amount_due: number;
          amount_paid: number;
          currency: string;
          line_items: Record<string, any>;
          invoice_date: string;
          due_date: string | null;
          created_at: string;
          paid_at: string | null;
          pdf_url: string | null;
          hosted_invoice_url: string | null;
          attempt_count: number;
          next_payment_attempt: string | null;
          metadata: Record<string, any>;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          subscription_id?: string | null;
          stripe_invoice_id: string;
          stripe_charge_id?: string | null;
          status: string;
          amount?: number;
          amount_due: number;
          amount_paid?: number;
          currency?: string;
          line_items?: Record<string, any>;
          invoice_date: string;
          due_date?: string | null;
          created_at?: string;
          paid_at?: string | null;
          pdf_url?: string | null;
          hosted_invoice_url?: string | null;
          attempt_count?: number;
          next_payment_attempt?: string | null;
          metadata?: Record<string, any>;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          subscription_id?: string | null;
          stripe_invoice_id?: string;
          stripe_charge_id?: string | null;
          status?: string;
          amount?: number;
          amount_due?: number;
          amount_paid?: number;
          currency?: string;
          line_items?: Record<string, any>;
          invoice_date?: string;
          due_date?: string | null;
          created_at?: string;
          paid_at?: string | null;
          pdf_url?: string | null;
          hosted_invoice_url?: string | null;
          attempt_count?: number;
          next_payment_attempt?: string | null;
          metadata?: Record<string, any>;
          updated_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          plan_id: string;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          stripe_price_id: string;
          status: string;
          current_period_start: string | null;
          current_period_end: string | null;
          cancel_at_period_end: boolean;
          canceled_at: string | null;
          ended_at: string | null;
          trial_start: string | null;
          trial_end: string | null;
          metadata: Record<string, any>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          plan_id: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_price_id: string;
          status?: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          canceled_at?: string | null;
          ended_at?: string | null;
          trial_start?: string | null;
          trial_end?: string | null;
          metadata?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          plan_id?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_price_id?: string;
          status?: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          canceled_at?: string | null;
          ended_at?: string | null;
          trial_start?: string | null;
          trial_end?: string | null;
          metadata?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
      };
      subscription_plans: {
        Row: {
          id: string;
          stripe_price_id: string;
          stripe_product_id: string;
          name: string;
          slug: string;
          description: string | null;
          tier: string;
          billing_interval: string;
          price_amount: number;
          currency: string;
          max_units: number | null;
          max_properties: number | null;
          max_ai_requests_daily: number | null;
          storage_limit_gb: number | null;
          features: Record<string, any>;
          is_active: boolean;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          stripe_price_id: string;
          stripe_product_id: string;
          name: string;
          slug: string;
          description?: string | null;
          tier: string;
          billing_interval: string;
          price_amount?: number;
          currency?: string;
          max_units?: number | null;
          max_properties?: number | null;
          max_ai_requests_daily?: number | null;
          storage_limit_gb?: number | null;
          features?: Record<string, any>;
          is_active?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          stripe_price_id?: string;
          stripe_product_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          tier?: string;
          billing_interval?: string;
          price_amount?: number;
          currency?: string;
          max_units?: number | null;
          max_properties?: number | null;
          max_ai_requests_daily?: number | null;
          storage_limit_gb?: number | null;
          features?: Record<string, any>;
          is_active?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_settings: {
        Row: {
          id: string;
          user_id: string;
          ai_tone: string | null;
          email_notifications: boolean;
          sms_notifications: boolean;
          theme: string;
          language: string;
          timezone: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          ai_tone?: string | null;
          email_notifications?: boolean;
          sms_notifications?: boolean;
          theme?: string;
          language?: string;
          timezone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          ai_tone?: string | null;
          email_notifications?: boolean;
          sms_notifications?: boolean;
          theme?: string;
          language?: string;
          timezone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_feedback: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          message: string;
          status: string;
          rating: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          message: string;
          status?: string;
          rating?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          message?: string;
          status?: string;
          rating?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      bot_settings: {
        Row: {
          id: string;
          user_id: string;
          bot_token: string | null;
          webhook_url: string | null;
          is_active: boolean;
          config: Record<string, any>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          bot_token?: string | null;
          webhook_url?: string | null;
          is_active?: boolean;
          config?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          bot_token?: string | null;
          webhook_url?: string | null;
          is_active?: boolean;
          config?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Enums: {
      // Define enums here if needed
    };
  };
}

// Re-export for convenience
export type Tables = Database['public']['Tables'];
export type Enums = Database['public']['Enums'];
