import { useState, lazy, Suspense } from 'react';
import { FileText, Download, Wrench, FileSignature, Loader2, CheckCircle, X } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useApp } from '@/context/AppContext';

// Lazy load jsPDF - reduces initial bundle by ~300KB
const loadJsPDF = () => import('jspdf').then(module => module.default);

export type DocumentType = 'lease' | 'work-order';

interface DocumentGeneratorProps {
  defaultType?: DocumentType;
  unitId?: string;
  maintenanceId?: string;
}

interface LeaseData {
  landlordName: string;
  landlordAddress: string;
  tenantName: string;
  tenantAddress: string;
  propertyAddress: string;
  unitNumber: string;
  leaseStart: string;
  leaseEnd: string;
  monthlyRent: number;
  securityDeposit: number;
  leaseType: 'free-market' | 'rent-stabilized';
}

interface WorkOrderData {
  requestId: string;
  unitNumber: string;
  propertyAddress: string;
  tenantName: string;
  issueDescription: string;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  category: string;
  dateSubmitted: string;
  estimatedCost?: number;
}

export function DocumentGenerator({ defaultType = 'lease', unitId, maintenanceId }: DocumentGeneratorProps) {
  const { units, maintenanceRequests } = useApp();
  const [documentType, setDocumentType] = useState<DocumentType>(defaultType);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isComplete, setIsComplete] = useState(false);
  const [showModal, setShowModal] = useState(false);

  // Lease form state
  const [leaseData, setLeaseData] = useState<Partial<LeaseData>>({
    leaseType: 'free-market',
    monthlyRent: 0,
    securityDeposit: 0,
  });

  // Work order form state
  const [workOrderData, setWorkOrderData] = useState<Partial<WorkOrderData>>(({
    priority: 'medium',
    dateSubmitted: new Date().toISOString().split('T')[0],
  }));

  const generateLeasePDF = async () => {
    const jsPDF = await loadJsPDF();
    const doc = new jsPDF();
    const data = leaseData as LeaseData;
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(33, 37, 41);
    doc.text('RESIDENTIAL LEASE AGREEMENT', 105, 20, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setTextColor(108, 117, 125);
    doc.text('This Lease Agreement (the "Agreement") is entered into as of the date signed below.', 105, 30, { align: 'center' });
    
    // Parties
    doc.setFontSize(12);
    doc.setTextColor(33, 37, 41);
    doc.text('1. PARTIES', 20, 45);
    
    doc.setFontSize(10);
    doc.text(`Landlord: ${data.landlordName || '[Landlord Name]'}`, 25, 55);
    doc.text(`Address: ${data.landlordAddress || '[Landlord Address]'}`, 25, 62);
    doc.text(`Tenant: ${data.tenantName || '[Tenant Name]'}`, 25, 72);
    doc.text(`Address: ${data.tenantAddress || '[Tenant Address]'}`, 25, 79);
    
    // Property
    doc.setFontSize(12);
    doc.text('2. PROPERTY', 20, 95);
    
    doc.setFontSize(10);
    doc.text(`Property Address: ${data.propertyAddress || '[Property Address]'}`, 25, 105);
    doc.text(`Unit Number: ${data.unitNumber || '[Unit Number]'}`, 25, 112);
    doc.text(`Lease Type: ${data.leaseType === 'rent-stabilized' ? 'Rent Stabilized' : 'Free Market'}`, 25, 119);
    
    // Terms
    doc.setFontSize(12);
    doc.text('3. LEASE TERM', 20, 135);
    
    doc.setFontSize(10);
    doc.text(`Lease Start Date: ${data.leaseStart || '[Start Date]'}`, 25, 145);
    doc.text(`Lease End Date: ${data.leaseEnd || '[End Date]'}`, 25, 152);
    
    // Rent
    doc.setFontSize(12);
    doc.text('4. RENT AND DEPOSIT', 20, 168);
    
    doc.setFontSize(10);
    doc.text(`Monthly Rent: $${data.monthlyRent?.toLocaleString() || '[Amount]'}`, 25, 178);
    doc.text(`Security Deposit: $${data.securityDeposit?.toLocaleString() || '[Amount]'}`, 25, 185);
    doc.text('Rent is due on the 1st of each month.', 25, 192);
    
    // Signatures
    doc.setFontSize(12);
    doc.text('5. SIGNATURES', 20, 210);
    
    doc.setFontSize(10);
    doc.text('Landlord Signature: _________________________ Date: ___________', 25, 225);
    doc.text('Tenant Signature: _________________________ Date: ___________', 25, 245);
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(108, 117, 125);
    doc.text('Generated by LandlordBot - This is a template. Please consult with an attorney before use.', 105, 280, { align: 'center' });
    
    return doc;
  };

  const generateWorkOrderPDF = async () => {
    const jsPDF = await loadJsPDF();
    const doc = new jsPDF();
    const data = workOrderData as WorkOrderData;
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(33, 37, 41);
    doc.text('MAINTENANCE WORK ORDER', 105, 20, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setTextColor(108, 117, 125);
    doc.text(`Request ID: ${data.requestId || '[Request ID]'}`, 105, 30, { align: 'center' });
    
    // Request Details
    doc.setFontSize(12);
    doc.setTextColor(33, 37, 41);
    doc.text('1. REQUEST DETAILS', 20, 45);
    
    doc.setFontSize(10);
    doc.text(`Unit Number: ${data.unitNumber || '[Unit Number]'}`, 25, 55);
    doc.text(`Property Address: ${data.propertyAddress || '[Property Address]'}`, 25, 62);
    doc.text(`Tenant Name: ${data.tenantName || '[Tenant Name]'}`, 25, 69);
    doc.text(`Date Submitted: ${data.dateSubmitted || '[Date]'}`, 25, 76);
    doc.text(`Priority: ${(data.priority || 'medium').toUpperCase()}`, 25, 83);
    doc.text(`Category: ${data.category || '[Category]'}`, 25, 90);
    
    // Issue Description
    doc.setFontSize(12);
    doc.text('2. ISSUE DESCRIPTION', 20, 110);
    
    doc.setFontSize(10);
    const splitDescription = doc.splitTextToSize(data.issueDescription || '[Issue Description]', 160);
    doc.text(splitDescription, 25, 120);
    
    // Cost Estimate
    if (data.estimatedCost) {
      doc.setFontSize(12);
      doc.text('3. COST ESTIMATE', 20, 200);
      
      doc.setFontSize(10);
      doc.text(`Estimated Cost: $${data.estimatedCost.toLocaleString()}`, 25, 210);
    }
    
    // Assignment
    doc.setFontSize(12);
    doc.text(data.estimatedCost ? '4. ASSIGNMENT' : '3. ASSIGNMENT', 20, 230);
    
    doc.setFontSize(10);
    doc.text('Assigned To: _________________________', 25, 245);
    doc.text('Date Assigned: _________________________', 25, 255);
    doc.text('Expected Completion: _________________________', 25, 265);
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(108, 117, 125);
    doc.text('Generated by LandlordBot - Work Order Template', 105, 280, { align: 'center' });
    
    return doc;
  };

  const handleGenerate = async () => {
    setIsGenerating(true);
    
    try {
      let doc;
      let fileName: string;
      
      if (documentType === 'lease') {
        doc = await generateLeasePDF();
        fileName = `lease-agreement-${leaseData.tenantName || 'template'}.pdf`;
      } else {
        doc = await generateWorkOrderPDF();
        fileName = `work-order-${workOrderData.requestId || 'template'}.pdf`;
      }
      
      doc.save(fileName);
      
      setIsComplete(true);
      setTimeout(() => {
        setIsComplete(false);
        setShowModal(false);
      }, 2000);
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Failed to generate PDF. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownload = async () => {
    setIsGenerating(true);
    
    try {
      // Generate and download
      let doc;
      let fileName: string;
      
      if (documentType === 'lease') {
        doc = await generateLeasePDF();
        fileName = `lease-agreement-${leaseData.tenantName || 'template'}.pdf`;
      } else {
        doc = await generateWorkOrderPDF();
        fileName = `work-order-${workOrderData.requestId || 'template'}.pdf`;
      }
      
      doc.save(fileName);
    } catch (error) {
      console.error('Error downloading PDF:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const autoFillFromUnit = (unitId: string) => {
    const unit = units.find(u => u.id === unitId);
    if (unit) {
      setWorkOrderData(prev => ({
        ...prev,
        unitNumber: unit.unitNumber,
        propertyAddress: unit.address || '',
      }));
      
      setLeaseData(prev => ({
        ...prev,
        unitNumber: unit.unitNumber,
        propertyAddress: unit.address || '',
        monthlyRent: unit.monthlyRent || unit.rentAmount || 0,
      }));
    }
  };

  const autoFillFromMaintenance = (maintenanceId: string) => {
    const request = maintenanceRequests.find(r => r.id === maintenanceId);
    if (request) {
      // Map priority to WorkOrderData priority (strip 'emergency' to 'urgent')
      const mappedPriority: WorkOrderData['priority'] = 
        request.priority === 'emergency' ? 'urgent' : 
        ['low', 'medium', 'high', 'urgent'].includes(request.priority) ? 
          request.priority as WorkOrderData['priority'] : 'medium';
      
      setWorkOrderData(prev => ({
        ...prev,
        requestId: request.id,
        unitNumber: request.unitNumber,
        issueDescription: request.description,
        priority: mappedPriority,
        category: request.category || 'general',
        dateSubmitted: request.createdAt?.split('T')[0] || new Date().toISOString().split('T')[0],
      }));
      
      // Also try to get property address
      const unit = units.find(u => u.unitNumber === request.unitNumber);
      if (unit) {
        setWorkOrderData(prev => ({
          ...prev,
          propertyAddress: unit.address || '',
        }));
      }
    }
  };

  return (
    <>
      {/* Trigger Button */}
      <motion.button
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        onClick={() => {
          // Pre-fill data if IDs provided
          if (unitId) autoFillFromUnit(unitId);
          if (maintenanceId) autoFillFromMaintenance(maintenanceId);
          setShowModal(true);
        }}
        className="inline-flex items-center gap-2 px-4 py-2 bg-amber-100 text-amber-900 rounded-lg font-medium hover:bg-amber-200 transition-colors"
      >
        <FileText className="w-4 h-4" />
        Generate Document
      </motion.button>

      {/* Document Generator Modal */}
      <AnimatePresence>
        {showModal && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm"
            onClick={() => !isGenerating && setShowModal(false)}
          >
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              onClick={(e) => e.stopPropagation()}
              className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto"
            >
              {/* Header */}
              <div className="flex items-center justify-between p-6 border-b">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-amber-100 rounded-lg">
                    <FileSignature className="w-5 h-5 text-amber-600" />
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold text-slate-900">Document Generator</h3>
                    <p className="text-sm text-slate-500">Generate professional documents instantly</p>
                  </div>
                </div>
                {!isGenerating && (
                  <button
                    onClick={() => setShowModal(false)}
                    className="p-2 text-slate-400 hover:text-slate-600 transition-colors"
                  >
                    <X className="w-5 h-5" />
                  </button>
                )}
              </div>

              {/* Document Type Tabs */}
              <div className="p-6 border-b">
                <div className="flex gap-2">
                  <button
                    onClick={() => setDocumentType('lease')}
                    disabled={isGenerating}
                    className={`flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-lg border-2 transition-all ${
                      documentType === 'lease'
                        ? 'border-amber-500 bg-amber-50 text-amber-900'
                        : 'border-slate-200 hover:border-slate-300'
                    }`}
                  >
                    <FileSignature className="w-4 h-4" />
                    Lease Agreement
                  </button>
                  <button
                    onClick={() => setDocumentType('work-order')}
                    disabled={isGenerating}
                    className={`flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-lg border-2 transition-all ${
                      documentType === 'work-order'
                        ? 'border-amber-500 bg-amber-50 text-amber-900'
                        : 'border-slate-200 hover:border-slate-300'
                    }`}
                  >
                    <Wrench className="w-4 h-4" />
                    Work Order
                  </button>
                </div>
              </div>

              {/* Form Content */}
              {isComplete ? (
                <div className="p-12 flex flex-col items-center justify-center text-center">
                  <motion.div
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mb-4"
                  >
                    <CheckCircle className="w-8 h-8 text-green-600" />
                  </motion.div>
                  <h4 className="text-lg font-semibold text-slate-900">Document Generated!</h4>
                  <p className="text-slate-500">Your PDF has been downloaded.</p>
                </div>
              ) : (
                <div className="p-6 space-y-6">
                  {documentType === 'lease' ? (
                    <div className="space-y-4">
                      <div className="text-sm font-medium text-slate-900">1. Parties</div>
                      <div className="grid grid-cols-2 gap-4">
                        <input
                          type="text"
                          placeholder="Landlord Name"
                          value={leaseData.landlordName || ''}
                          onChange={(e) => setLeaseData({ ...leaseData, landlordName: e.target.value })}
                          disabled={isGenerating}
                          className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-amber-500"
                        />
                        <input
                          type="text"
                          placeholder="Tenant Name"
                          value={leaseData.tenantName || ''}
                          onChange={(e) => setLeaseData({ ...leaseData, tenantName: e.target.value })}
                          disabled={isGenerating}
                          className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-amber-500"
                        />
                      </div>
                      <div className="grid grid-cols-2 gap-4">
                        <input
                          type="text"
                          placeholder="Landlord Address"
                          value={leaseData.landlordAddress || ''}
                          onChange={(e) => setLeaseData({ ...leaseData, landlordAddress: e.target.value })}
                          disabled={isGenerating}
                          className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-amber-500"
                        />
                        <input
                          type="text"
                          placeholder="Tenant Address"
                          value={leaseData.tenantAddress || ''}
                          onChange={(e) => setLeaseData({ ...leaseData, tenantAddress: e.target.value })}
                          disabled={isGenerating}
                          className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-amber-500"
                        />
                      </div>

                      <div className="text-sm font-medium text-slate-900">2. Property Information</div>
                      <div className="grid grid-cols-2 gap-4">
                        <input
                          type="text"
                          placeholder="Property Address"
                          value={leaseData.propertyAddress || ''}
                          onChange={(e) => setLeaseData({ ...leaseData, propertyAddress: e.target.value })}
                          disabled={isGenerating}
                          className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-amber-500"
                        />
                        <input
                          type="text"
                          placeholder="Unit Number"
                          value={leaseData.unitNumber || ''}
                          onChange={(e) => setLeaseData({ ...leaseData, unitNumber: e.target.value })}
                          disabled={isGenerating}
                          className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-amber-500"
                        />
                      </div>

                      <div className="text-sm font-medium text-slate-900">3. Lease Terms</div>
                      <div className="grid grid-cols-3 gap-4">
                        <select
                          value={leaseData.leaseType}
                          onChange={(e) => setLeaseData({ ...leaseData, leaseType: e.target.value as LeaseData['leaseType'] })}
                          disabled={isGenerating}
                          className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-amber-500"
                        >
                          <option value="free-market">Free Market</option>
                          <option value="rent-stabilized">Rent Stabilized</option>
                        </select>
                        <input
                          type="date"
                          placeholder="Start Date"
                          value={leaseData.leaseStart || ''}
                          onChange={(e) => setLeaseData({ ...leaseData, leaseStart: e.target.value })}
                          disabled={isGenerating}
                          className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-amber-500"
                        />
                        <input
                          type="date"
                          placeholder="End Date"
                          value={leaseData.leaseEnd || ''}
                          onChange={(e) => setLeaseData({ ...leaseData, leaseEnd: e.target.value })}
                          disabled={isGenerating}
                          className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-amber-500"
                        />
                      </div>

                      <div className="text-sm font-medium text-slate-900">4. Financial Terms</div>
                      <div className="grid grid-cols-2 gap-4">
                        <input
                          type="number"
                          placeholder="Monthly Rent ($)"
                          value={leaseData.monthlyRent || ''}
                          onChange={(e) => setLeaseData({ ...leaseData, monthlyRent: Number(e.target.value) })}
                          disabled={isGenerating}
                          className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-amber-500"
                        />
                        <input
                          type="number"
                          placeholder="Security Deposit ($)"
                          value={leaseData.securityDeposit || ''}
                          onChange={(e) => setLeaseData({ ...leaseData, securityDeposit: Number(e.target.value) })}
                          disabled={isGenerating}
                          className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-amber-500"
                        />
                      </div>
                    </div>
                  ) : (
                    <div className="space-y-4">
                      <div className="text-sm font-medium text-slate-900">1. Request Information</div>
                      <div className="grid grid-cols-2 gap-4">
                        <input
                          type="text"
                          placeholder="Request ID"
                          value={workOrderData.requestId || ''}
                          onChange={(e) => setWorkOrderData({ ...workOrderData, requestId: e.target.value })}
                          disabled={isGenerating}
                          className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-amber-500"
                        />
                        <input
                          type="text"
                          placeholder="Unit Number"
                          value={workOrderData.unitNumber || ''}
                          onChange={(e) => setWorkOrderData({ ...workOrderData, unitNumber: e.target.value })}
                          disabled={isGenerating}
                          className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-amber-500"
                        />
                      </div>
                      <input
                        type="text"
                        placeholder="Property Address"
                        value={workOrderData.propertyAddress || ''}
                        onChange={(e) => setWorkOrderData({ ...workOrderData, propertyAddress: e.target.value })}
                        disabled={isGenerating}
                        className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-amber-500"
                      />

                      <div className="text-sm font-medium text-slate-900">2. Issue Details</div>
                      <textarea
                        rows={3}
                        placeholder="Issue description"
                        value={workOrderData.issueDescription || ''}
                        onChange={(e) => setWorkOrderData({ ...workOrderData, issueDescription: e.target.value })}
                        disabled={isGenerating}
                        className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-amber-500"
                      />

                      <div className="grid grid-cols-3 gap-4">
                        <select
                          value={workOrderData.priority}
                          onChange={(e) => setWorkOrderData({ ...workOrderData, priority: e.target.value as WorkOrderData['priority'] })}
                          disabled={isGenerating}
                          className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-amber-500"
                        >
                          <option value="urgent">🔴 Urgent</option>
                          <option value="high">🟠 High</option>
                          <option value="medium">🟡 Medium</option>
                          <option value="low">🟢 Low</option>
                        </select>
                        <select
                          value={workOrderData.category || 'general'}
                          onChange={(e) => setWorkOrderData({ ...workOrderData, category: e.target.value })}
                          disabled={isGenerating}
                          className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-amber-500"
                        >
                          <option value="plumbing">Plumbing</option>
                          <option value="electrical">Electrical</option>
                          <option value="hvac">HVAC</option>
                          <option value="appliance">Appliance</option>
                          <option value="structural">Structural</option>
                          <option value="general">General</option>
                        </select>
                        <input
                          type="date"
                          value={workOrderData.dateSubmitted || ''}
                          onChange={(e) => setWorkOrderData({ ...workOrderData, dateSubmitted: e.target.value })}
                          disabled={isGenerating}
                          className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-amber-500"
                        />
                      </div>

                      <div className="text-sm font-medium text-slate-900">3. Cost Estimate (Optional)</div>
                      <input
                        type="number"
                        placeholder="Estimated Cost ($)"
                        value={workOrderData.estimatedCost || ''}
                        onChange={(e) => setWorkOrderData({ ...workOrderData, estimatedCost: Number(e.target.value) })}
                        disabled={isGenerating}
                        className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-amber-500"
                      />
                    </div>
                  )}
                </div>
              )}

              {/* Footer Actions */}
              {!isComplete && (
                <div className="flex items-center justify-end gap-3 p-6 border-t bg-slate-50">
                  <button
                    onClick={() => setShowModal(false)}
                    disabled={isGenerating}
                    className="px-4 py-2 text-slate-600 hover:text-slate-800 transition-colors disabled:opacity-50"
                  >
                    Cancel
                  </button>
                  <motion.button
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                    onClick={handleGenerate}
                    disabled={isGenerating}
                    className="flex items-center gap-2 px-6 py-2 bg-amber-500 text-white rounded-lg font-medium hover:bg-amber-600 transition-colors disabled:opacity-50"
                  >
                    {isGenerating ? (
                      <>
                        <Loader2 className="w-4 h-4 animate-spin" />
                        Generating...
                      </>
                    ) : (
                      <>
                        <Download className="w-4 h-4" />
                        Generate & Download PDF
                      </>
                    )}
                  </motion.button>
                </div>
              )}
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
