import { useState } from 'react';
import { FileText, Download, Wrench, FileSignature, Loader2, CheckCircle, X } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useApp } from '@/context/AppContext';
import jsPDF from 'jspdf';

export type DocumentType = 'lease' | 'work-order';

interface DocumentGeneratorProps {
  defaultType?: DocumentType;
  unitId?: string;
  maintenanceId?: string;
}

interface LeaseData {
  landlordName: string;
  landlordAddress: string;
  tenantName: string;
  tenantAddress: string;
  propertyAddress: string;
  unitNumber: string;
  leaseStart: string;
  leaseEnd: string;
  monthlyRent: number;
  securityDeposit: number;
  leaseType: 'free-market' | 'rent-stabilized';
}

interface WorkOrderData {
  requestId: string;
  unitNumber: string;
  propertyAddress: string;
  tenantName: string;
  issueDescription: string;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  category: string;
  dateSubmitted: string;
  estimatedCost?: number;
}

export function DocumentGenerator({ defaultType = 'lease', unitId, maintenanceId }: DocumentGeneratorProps) {
  const { units, maintenanceRequests } = useApp();
  const [documentType, setDocumentType] = useState<DocumentType>(defaultType);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isComplete, setIsComplete] = useState(false);
  const [showModal, setShowModal] = useState(false);

  // Lease form state
  const [leaseData, setLeaseData] = useState<Partial<LeaseData>>({
    leaseType: 'free-market',
    monthlyRent: 0,
    securityDeposit: 0,
  });

  // Work order form state
  const [workOrderData, setWorkOrderData] = useState<Partial<WorkOrderData>>({
    priority: 'medium',
    dateSubmitted: new Date().toISOString().split('T')[0],
  });

  const generateLeasePDF = () => {
    const doc = new jsPDF();
    const data = leaseData as LeaseData;
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(33, 37, 41);
    doc.text('RESIDENTIAL LEASE AGREEMENT', 105, 20, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setTextColor(108, 117, 125);
    doc.text('This Lease Agreement (the "Agreement") is entered into as of the date signed below.', 105, 30, { align: 'center' });
    
    // Parties
    doc.setFontSize(12);
    doc.setTextColor(33, 37, 41);
    doc.text('1. PARTIES', 20, 45);
    
    doc.setFontSize(10);
    doc.text(`Landlord: ${data.landlordName || '[Landlord Name]'}`, 25, 55);
    doc.text(`Address: ${data.landlordAddress || '[Landlord Address]'}`, 25, 62);
    doc.text(`Tenant: ${data.tenantName || '[Tenant Name]'}`, 25, 72);
    doc.text(`Address: ${data.tenantAddress || '[Tenant Address]'}`, 25, 79);
    
    // Property
    doc.setFontSize(12);
    doc.text('2. PROPERTY', 20, 95);
    
    doc.setFontSize(10);
    doc.text(`Property Address: ${data.propertyAddress || '[Property Address]'}`, 25, 105);
    doc.text(`Unit Number: ${data.unitNumber || '[Unit Number]'}`, 25, 112);
    doc.text(`Lease Type: ${data.leaseType === 'rent-stabilized' ? 'Rent Stabilized' : 'Free Market'}`, 25, 119);
    
    // Terms
    doc.setFontSize(12);
    doc.text('3. LEASE TERM', 20, 135);
    
    doc.setFontSize(10);
    doc.text(`Lease Start Date: ${data.leaseStart || '[Start Date]'}`, 25, 145);
    doc.text(`Lease End Date: ${data.leaseEnd || '[End Date]'}`, 25, 152);
    
    // Rent
    doc.setFontSize(12);
    doc.text('4. RENT AND DEPOSIT', 20, 168);
    
    doc.setFontSize(10);
    doc.text(`Monthly Rent: $${data.monthlyRent?.toLocaleString() || '[Amount]'}`, 25, 178);
    doc.text(`Security Deposit: $${data.securityDeposit?.toLocaleString() || '[Amount]'}`, 25, 185);
    doc.text('Rent is due on the 1st of each month.', 25, 192);
    
    // Signatures
    doc.setFontSize(12);
    doc.text('5. SIGNATURES', 20, 210);
    
    doc.setFontSize(10);
    doc.text('Landlord Signature: _________________________ Date: ___________', 25, 225);
    doc.text('Tenant Signature: _________________________ Date: ___________', 25, 245);
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(108, 117, 125);
    doc.text('Generated by LandlordBot - This is a template. Please consult with an attorney before use.', 105, 280, { align: 'center' });
    
    return doc;
  };

  const generateWorkOrderPDF = () => {
    const doc = new jsPDF();
    const data = workOrderData as WorkOrderData;
    
    // Header
    doc.setFillColor(245, 158, 11);
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setFontSize(24);
    doc.setTextColor(255, 255, 255);
    doc.text('WORK ORDER', 105, 25, { align: 'center' });
    
    // Work Order Info
    doc.setFontSize(12);
    doc.setTextColor(33, 37, 41);
    doc.text(`Work Order #: ${data.requestId || 'WO-XXXX'}`, 20, 55);
    doc.text(`Date: ${data.dateSubmitted || new Date().toLocaleDateString()}`, 120, 55);
    
    // Priority Badge
    const priorityColors = {
      low: [108, 117, 125],
      medium: [245, 158, 11],
      high: [220, 53, 69],
      urgent: [185, 28, 28],
    };
    const color = priorityColors[data.priority || 'medium'];
    doc.setFillColor(color[0], color[1], color[2]);
    doc.roundedRect(160, 62, 30, 10, 2, 2, 'F');
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.text((data.priority || 'MEDIUM').toUpperCase(), 175, 69, { align: 'center' });
    
    // Property Info
    doc.setFontSize(12);
    doc.setTextColor(33, 37, 41);
    doc.text('PROPERTY INFORMATION', 20, 85);
    
    doc.setFontSize(10);
    doc.setTextColor(108, 117, 125);
    doc.text(`Property Address: ${data.propertyAddress || '[Property Address]'}`, 25, 95);
    doc.text(`Unit Number: ${data.unitNumber || '[Unit Number]'}`, 25, 102);
    doc.text(`Tenant Name: ${data.tenantName || '[Tenant Name]'}`, 25, 109);
    
    // Issue Description
    doc.setFontSize(12);
    doc.setTextColor(33, 37, 41);
    doc.text('ISSUE DESCRIPTION', 20, 125);
    
    doc.setFontSize(10);
    doc.setTextColor(108, 117, 125);
    const splitDescription = doc.splitTextToSize(data.issueDescription || '[No description provided]', 170);
    doc.text(splitDescription, 25, 135);
    
    // Category
    doc.setFontSize(12);
    doc.setTextColor(33, 37, 41);
    doc.text('CATEGORY', 20, 165);
    
    doc.setFontSize(10);
    doc.setTextColor(108, 117, 125);
    doc.text(data.category || '[Category]', 25, 175);
    
    // Cost Estimate
    if (data.estimatedCost) {
      doc.setFontSize(12);
      doc.setTextColor(33, 37, 41);
      doc.text('ESTIMATED COST', 120, 165);
      
      doc.setFontSize(10);
      doc.setTextColor(108, 117, 125);
      doc.text(`$${data.estimatedCost.toLocaleString()}`, 125, 175);
    }
    
    // Signatures
    doc.setFontSize(12);
    doc.setTextColor(33, 37, 41);
    doc.text('AUTHORIZATION', 20, 210);
    
    doc.setFontSize(10);
    doc.setTextColor(108, 117, 125);
    doc.text('Landlord/Manager Signature: _________________________ Date: ___________', 25, 225);
    doc.text('Vendor Signature: _________________________ Date: ___________', 25, 245);
    doc.text('Completion Date: ___________', 25, 265);
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(108, 117, 125);
    doc.text('Generated by LandlordBot', 105, 280, { align: 'center' });
    
    return doc;
  };

  const handleGenerate = async () => {
    setIsGenerating(true);
    
    // Simulate generation delay
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    let doc;
    let filename;
    
    if (documentType === 'lease') {
      doc = generateLeasePDF();
      filename = `lease-agreement-${leaseData.tenantName?.replace(/\s+/g, '-').toLowerCase() || 'template'}.pdf`;
    } else {
      doc = generateWorkOrderPDF();
      filename = `work-order-${workOrderData.requestId || 'new'}.pdf`;
    }
    
    doc.save(filename);
    
    setIsGenerating(false);
    setIsComplete(true);
    
    setTimeout(() => {
      setIsComplete(false);
      setShowModal(false);
    }, 2000);
  };

  const openModal = () => {
    // Pre-fill data if unitId or maintenanceId is provided
    if (unitId) {
      const unit = units.find(u => u.id === unitId);
      if (unit) {
        setLeaseData(prev => ({
          ...prev,
          propertyAddress: unit.address,
          unitNumber: unit.unitNumber,
          monthlyRent: unit.rentAmount || 0,
        }));
        setWorkOrderData(prev => ({
          ...prev,
          propertyAddress: unit.address,
          unitNumber: unit.unitNumber,
          tenantName: unit.tenant?.name || '',
        }));
      }
    }
    
    if (maintenanceId) {
      const request = maintenanceRequests.find(r => r.id === maintenanceId);
      if (request) {
        const unit = units.find(u => u.id === request.unitId);
        setWorkOrderData(prev => ({
          ...prev,
          requestId: request.id.slice(0, 8).toUpperCase(),
          issueDescription: request.description,
          priority: request.priority as any,
          category: request.category || 'General',
          estimatedCost: request.costEstimate || undefined,
          propertyAddress: unit?.address || '',
          unitNumber: unit?.unitNumber || '',
          tenantName: unit?.tenant?.name || '',
        }));
        setDocumentType('work-order');
      }
    }
    
    setShowModal(true);
  };

  return (
    <>
      <button
        onClick={openModal}
        className="flex items-center gap-2 px-4 py-2 bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 dark:hover:bg-slate-600 text-slate-700 dark:text-slate-200 rounded-lg transition-colors"
      >
        <FileText className="w-4 h-4" />
        <span>Generate Document</span>
      </button>

      <AnimatePresence>
        {showModal && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4"
            onClick={() => setShowModal(false)}
          >
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              onClick={(e) => e.stopPropagation()}
              className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl max-w-2xl w-full max-h-[90vh] overflow-auto"
            >
              <div className="p-6 border-b border-slate-200 dark:border-slate-700 flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-amber-500/20 rounded-lg">
                    <FileSignature className="w-5 h-5 text-amber-500" />
                  </div>
                  <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-100">
                    Generate Document
                  </h2>
                </div>
                <button
                  onClick={() => setShowModal(false)}
                  className="p-1 text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-200"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              <div className="p-6">
                {/* Document Type Selection */}
                <div className="flex gap-4 mb-6">
                  <button
                    onClick={() => setDocumentType('lease')}
                    className={`flex-1 p-4 rounded-lg border-2 transition-all ${
                      documentType === 'lease'
                        ? 'border-amber-500 bg-amber-50 dark:bg-amber-900/20'
                        : 'border-slate-200 dark:border-slate-700 hover:border-slate-300'
                    }`}
                  >
                    <FileText className={`w-6 h-6 mx-auto mb-2 ${
                      documentType === 'lease' ? 'text-amber-500' : 'text-slate-400'
                    }`} />
                    <p className={`font-medium ${
                      documentType === 'lease' ? 'text-slate-900 dark:text-slate-100' : 'text-slate-500'
                    }`}>
                      Lease Agreement
                    </p>
                  </button>
                  
                  <button
                    onClick={() => setDocumentType('work-order')}
                    className={`flex-1 p-4 rounded-lg border-2 transition-all ${
                      documentType === 'work-order'
                        ? 'border-amber-500 bg-amber-50 dark:bg-amber-900/20'
                        : 'border-slate-200 dark:border-slate-700 hover:border-slate-300'
                    }`}
                  >
                    <Wrench className={`w-6 h-6 mx-auto mb-2 ${
                      documentType === 'work-order' ? 'text-amber-500' : 'text-slate-400'
                    }`} />
                    <p className={`font-medium ${
                      documentType === 'work-order' ? 'text-slate-900 dark:text-slate-100' : 'text-slate-500'
                    }`}>
                      Work Order
                    </p>
                  </button>
                </div>

                {/* Form Fields */}
                {documentType === 'lease' ? (
                  <div className="space-y-4">
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="block text-sm font-medium text-slate-600 dark:text-slate-400 mb-1">
                          Landlord Name
                        </label>
                        <input
                          type="text"
                          value={leaseData.landlordName || ''}
                          onChange={(e) => setLeaseData({ ...leaseData, landlordName: e.target.value })}
                          className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-lg"
                        />
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-slate-600 dark:text-slate-400 mb-1">
                          Tenant Name
                        </label>
                        <input
                          type="text"
                          value={leaseData.tenantName || ''}
                          onChange={(e) => setLeaseData({ ...leaseData, tenantName: e.target.value })}
                          className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-lg"
                        />
                      </div>
                    </div>
                    
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="block text-sm font-medium text-slate-600 dark:text-slate-400 mb-1">
                          Property Address
                        </label>
                        <input
                          type="text"
                          value={leaseData.propertyAddress || ''}
                          onChange={(e) => setLeaseData({ ...leaseData, propertyAddress: e.target.value })}
                          className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-lg"
                        />
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-slate-600 dark:text-slate-400 mb-1">
                          Unit Number
                        </label>
                        <input
                          type="text"
                          value={leaseData.unitNumber || ''}
                          onChange={(e) => setLeaseData({ ...leaseData, unitNumber: e.target.value })}
                          className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-lg"
                        />
                      </div>
                    </div>
                    
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="block text-sm font-medium text-slate-600 dark:text-slate-400 mb-1">
                          Lease Start
                        </label>
                        <input
                          type="date"
                          value={leaseData.leaseStart || ''}
                          onChange={(e) => setLeaseData({ ...leaseData, leaseStart: e.target.value })}
                          className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-lg"
                        />
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-slate-600 dark:text-slate-400 mb-1">
                          Lease End
                        </label>
                        <input
                          type="date"
                          value={leaseData.leaseEnd || ''}
                          onChange={(e) => setLeaseData({ ...leaseData, leaseEnd: e.target.value })}
                          className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-lg"
                        />
                      </div>
                    </div>
                    
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="block text-sm font-medium text-slate-600 dark:text-slate-400 mb-1">
                          Monthly Rent ($)
                        </label>
                        <input
                          type="number"
                          value={leaseData.monthlyRent || ''}
                          onChange={(e) => setLeaseData({ ...leaseData, monthlyRent: parseInt(e.target.value) || 0 })}
                          className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-lg"
                        />
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-slate-600 dark:text-slate-400 mb-1">
                          Security Deposit ($)
                        </label>
                        <input
                          type="number"
                          value={leaseData.securityDeposit || ''}
                          onChange={(e) => setLeaseData({ ...leaseData, securityDeposit: parseInt(e.target.value) || 0 })}
                          className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-lg"
                        />
                      </div>
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium text-slate-600 dark:text-slate-400 mb-1">
                        Lease Type
                      </label>
                      <select
                        value={leaseData.leaseType}
                        onChange={(e) => setLeaseData({ ...leaseData, leaseType: e.target.value as any })}
                        className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-lg"
                      >
                        <option value="free-market">Free Market</option>
                        <option value="rent-stabilized">Rent Stabilized</option>
                      </select>
                    </div>
                  </div>
                ) : (
                  <div className="space-y-4">
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="block text-sm font-medium text-slate-600 dark:text-slate-400 mb-1">
                          Work Order ID
                        </label>
                        <input
                          type="text"
                          value={workOrderData.requestId || ''}
                          onChange={(e) => setWorkOrderData({ ...workOrderData, requestId: e.target.value })}
                          placeholder="WO-1234"
                          className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-lg"
                        />
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-slate-600 dark:text-slate-400 mb-1">
                          Date Submitted
                        </label>
                        <input
                          type="date"
                          value={workOrderData.dateSubmitted || ''}
                          onChange={(e) => setWorkOrderData({ ...workOrderData, dateSubmitted: e.target.value })}
                          className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-lg"
                        />
                      </div>
                    </div>
                    
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="block text-sm font-medium text-slate-600 dark:text-slate-400 mb-1">
                          Property Address
                        </label>
                        <input
                          type="text"
                          value={workOrderData.propertyAddress || ''}
                          onChange={(e) => setWorkOrderData({ ...workOrderData, propertyAddress: e.target.value })}
                          className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-lg"
                        />
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-slate-600 dark:text-slate-400 mb-1">
                          Unit Number
                        </label>
                        <input
                          type="text"
                          value={workOrderData.unitNumber || ''}
                          onChange={(e) => setWorkOrderData({ ...workOrderData, unitNumber: e.target.value })}
                          className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-lg"
                        />
                      </div>
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium text-slate-600 dark:text-slate-400 mb-1">
                        Tenant Name
                      </label>
                      <input
                        type="text"
                        value={workOrderData.tenantName || ''}
                        onChange={(e) => setWorkOrderData({ ...workOrderData, tenantName: e.target.value })}
                        className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-lg"
                      />
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium text-slate-600 dark:text-slate-400 mb-1">
                        Issue Description
                      </label>
                      <textarea
                        value={workOrderData.issueDescription || ''}
                        onChange={(e) => setWorkOrderData({ ...workOrderData, issueDescription: e.target.value })}
                        rows={3}
                        className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-lg resize-none"
                      />
                    </div>
                    
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="block text-sm font-medium text-slate-600 dark:text-slate-400 mb-1">
                          Priority
                        </label>
                        <select
                          value={workOrderData.priority}
                          onChange={(e) => setWorkOrderData({ ...workOrderData, priority: e.target.value as any })}
                          className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-lg"
                        >
                          <option value="low">Low</option>
                          <option value="medium">Medium</option>
                          <option value="high">High</option>
                          <option value="urgent">Urgent</option>
                        </select>
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-slate-600 dark:text-slate-400 mb-1">
                          Category
                        </label>
                        <select
                          value={workOrderData.category || ''}
                          onChange={(e) => setWorkOrderData({ ...workOrderData, category: e.target.value })}
                          className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-lg"
                        >
                          <option value="">Select category...</option>
                          <option value="Plumbing">Plumbing</option>
                          <option value="Electrical">Electrical</option>
                          <option value="HVAC">HVAC</option>
                          <option value="Appliance">Appliance</option>
                          <option value="General Repair">General Repair</option>
                          <option value="Cleaning">Cleaning</option>
                          <option value="Other">Other</option>
                        </select>
                      </div>
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium text-slate-600 dark:text-slate-400 mb-1">
                        Estimated Cost ($)
                      </label>
                      <input
                        type="number"
                        value={workOrderData.estimatedCost || ''}
                        onChange={(e) => setWorkOrderData({ ...workOrderData, estimatedCost: parseInt(e.target.value) || undefined })}
                        className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-700 border border-slate-200 dark:border-slate-600 rounded-lg"
                      />
                    </div>
                  </div>
                )}

                {/* Actions */}
                <div className="flex gap-3 mt-6 pt-4 border-t border-slate-200 dark:border-slate-700">
                  <button
                    onClick={handleGenerate}
                    disabled={isGenerating || isComplete}
                    className="flex-1 flex items-center justify-center gap-2 px-4 py-3 bg-amber-500 hover:bg-amber-600 disabled:bg-slate-300 text-white font-medium rounded-lg transition-colors"
                  >
                    {isGenerating ? (
                      <><Loader2 className="w-4 h-4 animate-spin" /> <span>Generating...</span></>
                    ) : isComplete ? (
                      <><CheckCircle className="w-4 h-4" /> <span>Downloaded!</span></>
                    ) : (
                      <><Download className="w-4 h-4" /> <span>Generate PDF</span></>
                    )}
                  </button>
                  
                  <button
                    onClick={() => setShowModal(false)}
                    className="px-6 py-3 border border-slate-300 dark:border-slate-600 text-slate-700 dark:text-slate-300 font-medium rounded-lg hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors"
                  >
                    Cancel
                  </button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}

export default DocumentGenerator;
